# -*- coding: utf-8 -*-
"""reproducibility_code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vzKUnx1ZyFP1nwtrLyTrPTm_TOF7SmGX
"""

import os
import re
import subprocess
import tempfile
import numpy as np
from pathlib import Path
from typing import List, Dict, Tuple, Optional
import json
import random
from collections import defaultdict

# PDDL COMPILER

class PDDLCompiler:

    def __init__(self, domain_path: str, problem_path: str):
        self.domain_path = Path(domain_path)
        self.problem_path = Path(problem_path)
        self.domain_content = self.problem_path.read_text()

    def compile_compliant(self, observations: List[str], output_dir: Path) -> Tuple[Path, Path]:
        domain_out = output_dir / compliant_domain.pddl
        problem_out = output_dir / compliant_problem.pddl


        self._add_observation_tracking(observations, domain_out, problem_out, compliant=True)

        return domain_out, problem_out

    def compile_noncompliant(self, observations: List[str], output_dir: Path) -> Tuple[Path, Path]:
        domain_out = output_dir / noncompliant_domain.pddl
        problem_out = output_dir / noncompliant_problem.pddl

        self._add_observation_tracking(observations, domain_out, problem_out, compliant=False)

        return domain_out, problem_out

    def _add_observation_tracking(self, observations, domain_out, problem_out, compliant):
        pass


# ============================================================================
# PLANNER INTEGRATION
# ============================================================================

class FastDownwardPlanner:
    """Wrapper for calling Fast Downward and extracting plan costs"""

    def __init__(self, fd_path: str, timeout: int = 300):
        self.fd_path = Path(fd_path)
        self.timeout = timeout

    def get_plan_cost(self, domain_file: Path, problem_file: Path) -> Optional[float]:
        """Run Fast Downward and return minimal plan cost"""
        # Command for Fast Downward with A* and LM-Cut heuristic
        cmd = [
            str(self.fd_path / "fast-downward.py"),
            "--alias", "seq-opt-lmcut",  # Optimal planning with LM-Cut
            "--overall-time-limit", str(self.timeout),
            str(domain_file),
            str(problem_file)
        ]

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=self.timeout + 10
            )

            # Parse cost from output
            cost = self._parse_cost(result.stdout)
            return cost

        except subprocess.TimeoutExpired:
            print(f"Timeout on {domain_file}")
            return float('inf')
        except Exception as e:
            print(f"Error: {e}")
            return None

    def _parse_cost(self, output: str) -> Optional[float]:
        """Extract plan cost from Fast Downward output"""
        # Look for "Plan length: X" or "Cost: Y"
        match = re.search(r"Plan cost: (\d+)", output)
        if match:
            return float(match.group(1))

        match = re.search(r"Plan length: (\d+)", output)
        if match:
            return float(match.group(1))

        return float('inf')


# ============================================================================
# BAYESIAN GOAL RECOGNITION
# ============================================================================

class GoalRecognizer:
    """Main recognizer implementing Ramirez & Geffner 2010"""

    def __init__(self, planner: FastDownwardPlanner, beta: float = 1.0):
        self.planner = planner
        self.beta = beta

    def recognize(self, domain_file: Path,
                  problems: Dict[str, Path],  # goal_name -> problem_file
                  observations: List[str],
                  temp_dir: Path) -> Dict[str, float]:
        """
        Recognize goal from observations

        Args:
            domain_file: Path to domain PDDL
            problems: Dict mapping goal names to problem PDDL files
            observations: List of observed action names
            temp_dir: Directory for temporary compiled files

        Returns:
            Dictionary mapping goal names to posterior probabilities
        """
        compiler = PDDLCompiler(str(domain_file), "")
        costs = {}

        for goal_name, problem_file in problems.items():
            # Compliant problem
            comp_domain, comp_problem = compiler.compile_compliant(
                observations, temp_dir
            )
            cost_comp = self.planner.get_plan_cost(comp_domain, comp_problem)

            # Non-compliant problem
            non_domain, non_problem = compiler.compile_noncompliant(
                observations, temp_dir
            )
            cost_non = self.planner.get_plan_cost(non_domain, non_problem)

            # Delta and likelihood
            delta = cost_non - cost_comp if cost_non != float('inf') else -1e6
            costs[goal_name] = delta

        # Boltzmann likelihoods
        max_delta = max(costs.values())
        likelihoods = {}
        for goal, delta in costs.items():
            # Numerical stability: subtract max
            likelihoods[goal] = np.exp(self.beta * (delta - max_delta))

        # Normalize to posterior
        total = sum(likelihoods.values())
        posteriors = {g: l/total for g, l in likelihoods.items()}

        return posteriors


# ============================================================================
# EXPERIMENT PIPELINE
# ============================================================================

class ExperimentRunner:
    """Runs full reproducibility experiments"""

    def __init__(self, planner_path: str, domains_dir: Path, output_dir: Path):
        self.planner = FastDownwardPlanner(planner_path)
        self.recognizer = GoalRecognizer(self.planner, beta=1.0)
        self.domains_dir = domains_dir
        self.output_dir = output_dir
        self.output_dir.mkdir(exist_ok=True)

    def run_domain(self, domain_name: str, num_seeds: int = 30):
        """Run experiments for a single domain"""
        domain_file = self.domains_dir / domain_name / "domain.pddl"
        problems_dir = self.domains_dir / domain_name / "problems"

        # Get all goal problems
        problem_files = list(problems_dir.glob("*.pddl"))
        goal_names = [p.stem for p in problem_files]
        problems = dict(zip(goal_names, problem_files))

        results = defaultdict(list)

        for seed in range(num_seeds):
            random.seed(seed)

            # For each goal as the true hidden goal
            for true_goal in goal_names:
                # Generate full plan for true goal
                full_plan = self._get_plan(domain_file, problems[true_goal])
                if not full_plan:
                    continue

                # Test different observation ratios
                for obs_ratio in [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]:
                    obs_len = max(1, int(len(full_plan) * obs_ratio))
                    observations = full_plan[:obs_len]

                    with tempfile.TemporaryDirectory() as tmpdir:
                        posteriors = self.recognizer.recognize(
                            domain_file, problems, observations, Path(tmpdir)
                        )

                    # Record metrics
                    true_posterior = posteriors.get(true_goal, 0)
                    rank = sorted(posteriors.items(), key=lambda x: -x[1])
                    true_rank = [i for i, (g, _) in enumerate(rank) if g == true_goal][0] + 1
                    is_correct = 1 if true_rank == 1 else 0

                    results[obs_ratio].append({
                        'true_goal': true_goal,
                        'true_posterior': true_posterior,
                        'rank': true_rank,
                        'accuracy': is_correct,
                        'seed': seed
                    })

        # Save results
        self._save_results(domain_name, results)
        return results

    def _get_plan(self, domain_file, problem_file) -> Optional[List[str]]:
        """Generate a plan for a problem"""
        # Simplified: In reality, run planner and extract action sequence
        # For reproduction, you'll need to actually run Fast Downward here
        return None

    def _save_results(self, domain_name, results):
        """Save results to JSON for analysis"""
        output_file = self.output_dir / f"{domain_name}_results.json"
        serializable = {}
        for obs_ratio, records in results.items():
            serializable[str(obs_ratio)] = [
                {k: v for k, v in r.items() if k != 'true_goal'}
                for r in records
            ]

        with open(output_file, 'w') as f:
            json.dump(serializable, f, indent=2)


# ============================================================================
# ANALYSIS AND REPORTING
# ============================================================================

def compute_statistics(results_file: Path) -> Dict:
    """Compute means, stds, confidence intervals from results"""
    with open(results_file, 'r') as f:
        data = json.load(f)

    stats = {}
    for obs_ratio, records in data.items():
        accuracies = [r['accuracy'] for r in records]
        posteriors = [r['true_posterior'] for r in records]
        ranks = [r['rank'] for r in records]

        n = len(accuracies)
        stats[obs_ratio] = {
            'accuracy_mean': np.mean(accuracies),
            'accuracy_std': np.std(accuracies),
            'accuracy_ci_95': 1.96 * np.std(accuracies) / np.sqrt(n),
            'posterior_mean': np.mean(posteriors),
            'posterior_std': np.std(posteriors),
            'rank_mean': np.mean(ranks),
            'n': n
        }

    return stats


def generate_latex_table(stats: Dict) -> str:
    lines = [
        r"\begin{table}[H]",
        r"\centering",
        r"\begin{tabular}{lcccc}",
        r"\toprule",
        r"\textbf{Observations \%}" + r" & \textbf{Accuracy} & \textbf{95\% CI} & \textbf{Posterior} & \textbf{Rank} \\",
        r"\midrule"
    ]

    for obs_ratio in sorted(stats.keys(), key=float):
        s = stats[obs_ratio]
        obs_pct = int(float(obs_ratio) * 100)
        lines.append(
            f"{obs_pct}\\% & "
            f"{s['accuracy_mean']:.3f} & "
            f"\u00b1{s['accuracy_ci_95']:.3f} & "
            f"{s['posterior_mean']:.3f} & "
            f"{s['rank_mean']:.2f} \\"
        )

    lines.extend([
        r"\bottomrule",
        r"\end{tabular}",
        r"\caption{Reproduction results across observation ratios}",
        r"\label{tab:results}",
        r"\end{table}"
    ])

    return "\n".join(lines)


# ============================================================================
# MAIN
# ============================================================================

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Run PRAP reproducibility experiments")
    parser.add_argument("--planner", required=True, help="Path to Fast Downward directory")
    parser.add_argument("--domains", required=True, help="Path to domains directory")
    parser.add_argument("--output", default="./results", help="Output directory")
    parser.add_argument("--seeds", type=int, default=30, help="Number of random seeds")
    parser.add_argument("--domain", help="Specific domain to run")
    args = parser.parse_args(["--planner", "/content/fast-downward", "--domains", "/content/pddl_domains"])

    runner = ExperimentRunner(args.planner, Path(args.domains), Path(args.output))

    if args.domain:
        results = runner.run_domain(args.domain, args.seeds)
    else:
        # Run all 6 domains
        domains = ["block_words", "logistics", "grid", "blocks_world", "depots", "rover"]
        for domain in domains:
            print(f"Running {domain}...")
            results = runner.run_domain(domain, args.seeds)

import re
import subprocess
import tempfile
import os
from pathlib import Path
from typing import List, Tuple, Dict, Optional
from dataclasses import dataclass
import numpy as np


@dataclass
class Observation:
    action_name: str
    parameters: List[str]

    def to_pddl(self) -> str:
        if self.parameters:
            return f"({self.action_name} {' '.join(self.parameters)})"
        return f"({self.action_name})"

    def get_predicate_name(self) -> str:
        return f"obs_{self.action_name}_{'_'.join(self.parameters)}"


@dataclass
class PlanningResult:
    success: bool
    plan_cost: float
    plan_length: int
    plan_actions: List[str]
    runtime: float


class PDDLCompiler:

    def __init__(self, domain_path: str, problem_path: str):

        self.domain_path = Path(domain_path)
        self.problem_path = Path(problem_path)


        self.domain_content = self.domain_path.read_text()
        self.problem_content = self.problem_path.read_text()

        # Extract domain name and problem name
        self.domain_name = self._extract_domain_name()
        self.problem_name = self._extract_problem_name()

        # Extract original goal
        self.original_goal = self._extract_goal()

        # Extract objects and their types
        self.objects = self._extract_objects()

        # Extract action schemas from domain
        self.actions = self._extract_actions()

    def _extract_domain_name(self) -> str:

        match = re.search(r'\(domain\s+(\S+)\)', self.domain_content)
        if match:
            return match.group(1)
        return "unknown"

    def _extract_problem_name(self) -> str:

        match = re.search(r'\(problem\s+(\S+)\)', self.problem_content)
        if match:
            return match.group(1)
        return "unknown"

    def _extract_goal(self) -> str:

        # Find the goal section
        goal_pattern = r'\(:goal\s+(.+?)\)(?:\s|$|\(:|\n)'
        match = re.search(goal_pattern, self.problem_content, re.DOTALL)
        if match:
            goal = match.group(1).strip()

            return goal
        return ""

    def _extract_objects(self) -> Dict[str, List[str]]:

        objects = {}
        obj_pattern = r'\(:objects\s+(.+?)\)(?:\s|$|\(:|\n)'
        match = re.search(obj_pattern, self.problem_content, re.DOTALL)
        if match:
            obj_decl = match.group(1)
            # Parse tokens, handling types (e.g., "a b c - type")
            tokens = obj_decl.strip().split()
            current_type = "object"
            current_objs = []

            for token in tokens:
                if token == "-":
                    continue
                elif token in ["object", "thing"] or (current_type == "object" and token not in current_objs):
                    if current_objs:
                        objects[current_type] = current_objs
                        current_objs = []
                    current_type = token
                else:
                    current_objs.append(token)

            if current_objs:
                objects[current_type] = current_objs

        return objects

    def _extract_actions(self) -> List[Dict]:
        actions = []
        action_pattern = r'\(:action\s+(\S+)\s*:parameters\s*\((.+?)\)\s*:precondition\s*(.+?)\s*:effect\s*(.+?)\)'

        for match in re.finditer(action_pattern, self.domain_content, re.DOTALL):
            action = {
                'name': match.group(1),
                'parameters': match.group(2).strip(),
                'precondition': match.group(3).strip(),
                'effect': match.group(4).strip()
            }
            actions.append(action)

        return actions

    def compile_compliant(
        self,
        observations: List[Observation],
        output_dir: Optional[Path] = None
    ) -> Tuple[str, str]:

        if output_dir is None:
            output_dir = Path(tempfile.mkdtemp())
        else:
            output_dir = Path(output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)

        # Create augmented domain
        augmented_domain = self._create_compliant_domain(observations)
        domain_out = output_dir / f"{self.domain_name}_compliant.pddl"
        domain_out.write_text(augmented_domain)

        # Create augmented problem
        augmented_problem = self._create_compliant_problem(observations)
        problem_out = output_dir / f"{self.problem_name}_compliant.pddl"
        problem_out.write_text(augmented_problem)

        return str(domain_out), str(problem_out)

    def _create_compliant_domain(self, observations: List[Observation]) -> str:

        # Add observation predicates
        obs_predicates = []
        for obs in observations:
            pred_name = obs.get_predicate_name()
            # Create predicate: (obs_<action> ?p1 ?p2 ...)
            params_str = " ".join([f"?p{i}" for i in range(len(obs.parameters))])
            obs_predicates.append(f"({pred_name} {params_str})")

        # Build new domain by modifying actions to add observation effects
        modified_actions = []

        for action in self.actions:
            # For each action that matches an observation, add the observation effect
            original_effect = action['effect']
            additional_effects = []

            for obs in observations:
                if self._action_matches_observation(action, obs):

                    pred_name = obs.get_predicate_name()
                    params_str = " ".join(obs.parameters)
                    additional_effects.append(f"({pred_name} {params_str})")

            if additional_effects:
                # Combine original effect with new effects
                if original_effect.startswith('(and'):
                    new_effect = original_effect[:-1] + " " + " ".join(additional_effects) + ")"
                else:

                    all_effects = [original_effect] + additional_effects
                    new_effect = f"(and {' '.join(all_effects)})"
            else:
                new_effect = original_effect

            # Create modified action
            modified_action = f"""
(:action {action['name']}
  :parameters ({action['parameters']})
  :precondition {action['precondition']}
  :effect {new_effect})
"""
            modified_actions.append(modified_action)

        # Build the complete domain
        obs_predicates_str = "\n    ".join(obs_predicates) if obs_predicates else ""

        # Find the existing predicates section
        pred_match = re.search(r'\(:predicates\s+(.+?)\)', self.domain_content, re.DOTALL)
        if pred_match:
            existing_preds = pred_match.group(1).strip()
            # Insert new predicates
            new_domain = self.domain_content.replace(
                f'(:predicates {existing_preds})',
                f'(:predicates {existing_preds} {" ".join(obs_predicates)})' if obs_predicates else f'(:predicates {existing_preds})'
            )
        else:
            # If no predicates section, add one
            pred_section = f'(:predicates\n    {" ".join(obs_predicates)})' if obs_predicates else '(:predicates)'
            # Insert after domain name
            domain_header = f'(domain {self.domain_name})'
            new_domain = self.domain_content.replace(
                domain_header,
                f'{domain_header}\n{pred_section}'
            )

        # Replace actions
        for i, action in enumerate(self.actions):
            original_action_str = self._extract_action_string(action['name'])
            if original_action_str:
                new_domain = new_domain.replace(original_action_str, modified_actions[i])

        return new_domain

    def _create_compliant_problem(self, observations: List[Observation]) -> str:


        obs_goals = []
        for obs in observations:
            pred_name = obs.get_predicate_name()
            params_str = " ".join(obs.parameters)
            obs_goals.append(f"({pred_name} {params_str})")

        # Combine original goal with observation goals
        if obs_goals:
            if self.original_goal:
                if self.original_goal.startswith('(and'):
                    # Insert into existing and
                    combined_goal = self.original_goal[:-1] + " " + " ".join(obs_goals) + ")"
                else:
                    combined_goal = f"(and {self.original_goal} {' '.join(obs_goals)})"
            else:
                combined_goal = f"(and {' '.join(obs_goals)})"
        else:
            combined_goal = self.original_goal

        # Build the new problem file
        new_problem = self.problem_content

        # Replace the goal
        goal_pattern = r'\(:goal\s+.+?\)'
        new_problem = re.sub(goal_pattern, f'(:goal {combined_goal})', new_problem, flags=re.DOTALL)

        return new_problem

    def compile_non_compliant(
        self,
        observations: List[Observation],
        output_dir: Optional[Path] = None
    ) -> Tuple[str, str]:

        if output_dir is None:
            output_dir = Path(tempfile.mkdtemp())
        else:
            output_dir = Path(output_dir)
            output_dir.mkdir(parents=True, exist_ok=True)


        augmented_domain = self._create_non_compliant_domain(observations)
        domain_out = output_dir / f"{self.domain_name}_noncompliant.pddl"
        domain_out.write_text(augmented_domain)

        augmented_problem = self._create_non_compliant_problem(observations)
        problem_out = output_dir / f"{self.problem_name}_noncompliant.pddl"
        problem_out.write_text(augmented_problem)

        return str(domain_out), str(problem_out)

    def _create_non_compliant_domain(self, observations: List[Observation]) -> str:


        forbidden_pred = "(forbidden)"

        # Add forbidden predicate to domain
        pred_match = re.search(r'\(:predicates\s+(.+?)\)', self.domain_content, re.DOTALL)
        if pred_match:
            existing_preds = pred_match.group(1).strip()
            new_domain = self.domain_content.replace(
                f'(:predicates {existing_preds})',
                f'(:predicates {existing_preds} {forbidden_pred})'
            )
        else:
            domain_header = f'(domain {self.domain_name})'
            new_domain = self.domain_content.replace(
                domain_header,
                f'{domain_header}\n(:predicates {forbidden_pred})'
            )


        return self.domain_content

    def _create_non_compliant_problem(self, observations: List[Observation]) -> str:

        return self.problem_content

    def _action_matches_observation(self, action: Dict, obs: Observation) -> bool:

        if action['name'] != obs.action_name:
            return False


        param_names = re.findall(r'\?(\w+)', action['parameters'])

        if len(param_names) != len(obs.parameters):
            return False

        return True

    def _extract_action_string(self, action_name: str) -> Optional[str]:

        pattern = rf'\(:action\s+{re.escape(action_name)}.+?\)(?=\s*\(:action|\s*\(:)\s*'
        match = re.search(pattern, self.domain_content, re.DOTALL)
        if match:
            return match.group(0)
        return None


class GoalRecognizer:


    def __init__(
        self,
        domain_path: str,
        problem_template: str,
        planner_command: List[str],
        beta: float = 0.5
    ):

        self.domain_path = Path(domain_path)
        self.problem_template = Path(problem_template)
        self.planner_command = planner_command
        self.beta = beta

    def compute_cost_difference(
        self,
        goal: str,
        observations: List[Observation],
        compiler: PDDLCompiler
    ) -> Tuple[float, float, float]:




        # Create problem with this goal
        problem = self._create_goal_problem(goal)

        # Compute compliant plan cost
        with tempfile.TemporaryDirectory() as tmpdir:
            tmp_path = Path(tmpdir)
            problem_file = tmp_path / "problem.pddl"
            problem_file.write_text(problem)

            # Create compiler for this goal-specific problem
            goal_compiler = PDDLCompiler(str(self.domain_path), str(problem_file))

            # Compile compliant version
            dom_compliant, prob_compliant = goal_compiler.compile_compliant(observations, tmp_path / "compliant")

            # Run planner for compliant
            compliant_result = self._run_planner(dom_compliant, prob_compliant)


            noncompliant_result = self._run_planner(str(self.domain_path), str(problem_file))

        compliant_cost = compliant_result.plan_cost if compliant_result.success else float('inf')
        noncompliant_cost = noncompliant_result.plan_cost if noncompliant_result.success else float('inf')

        delta = compliant_cost - noncompliant_cost

        return compliant_cost, noncompliant_cost, delta

    def _create_goal_problem(self, goal: str) -> str:

        problem_content = self.problem_template.read_text()

        # Replace goal placeholder
        goal_pattern = r'\(:goal\s+.+?\)'
        problem_content = re.sub(goal_pattern, f'(:goal {goal})', problem_content, flags=re.DOTALL)

        return problem_content

    def _run_planner(self, domain_path: str, problem_path: str) -> PlanningResult:

        import time


        start_time = time.time()



        plan_file = Path(tempfile.mktemp(suffix='.plan'))

        # Build command - customize for your planner
        cmd = self.planner_command + [domain_path, problem_path, '--plan-file', str(plan_file)]

        try:
            result = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=300  # 5 minute timeout
            )

            runtime = time.time() - start_time

            if result.returncode == 0 and plan_file.exists():
                plan_cost, plan_actions = self._parse_plan(plan_file)
                return PlanningResult(
                    success=True,
                    plan_cost=plan_cost,
                    plan_length=len(plan_actions),
                    plan_actions=plan_actions,
                    runtime=runtime
                )
            else:
                return PlanningResult(
                    success=False,
                    plan_cost=float('inf'),
                    plan_length=0,
                    plan_actions=[],
                    runtime=runtime
                )
        except subprocess.TimeoutExpired:
            return PlanningResult(
                success=False,
                plan_cost=float('inf'),
                plan_length=0,
                plan_actions=[],
                runtime=300
            )
        finally:
            if plan_file.exists():
                plan_file.unlink()

    def _parse_plan(self, plan_file: Path) -> Tuple[float, List[str]]:
        """Parse the plan file to extract actions and cost"""
        content = plan_file.read_text()

        # Look for cost in various formats
        cost = 1.0  # default cost per action

        # Some planners output "; cost = X" or "Plan cost: X"
        cost_match = re.search(r'cost\s*[=:]\s*(\d+(?:\.\d+)?)', content, re.IGNORECASE)
        if cost_match:
            total_cost = float(cost_match.group(1))
        else:
            # Count actions as cost
            actions = []
            for line in content.split('\n'):
                line = line.strip()
                if line and not line.startswith(';') and line.startswith('('):
                    actions.append(line)
            total_cost = float(len(actions))
            return total_cost, actions

        # Extract individual actions
        actions = re.findall(r'\([^)]+\)', content)
        actions = [a for a in actions if not a.startswith(';')]

        return total_cost, actions

    def compute_posterior(
        self,
        goals: List[str],
        observations: List[Observation],
        compiler: PDDLCompiler,
        prior: Optional[List[float]] = None
    ) -> Dict[str, float]:

        n_goals = len(goals)

        if prior is None:
            prior = [1.0 / n_goals] * n_goals

        # Compute likelihoods
        likelihoods = []
        deltas = []

        for goal in goals:
            _, _, delta = self.compute_cost_difference(goal, observations, compiler)
            deltas.append(delta)

            # Boltzmann likelihood
            likelihood = np.exp(self.beta * delta)
            likelihoods.append(likelihood)

        # Normalize to get P(O|G)
        likelihoods = np.array(likelihoods)
        likelihoods = likelihoods / likelihoods.sum()

        # Apply prior
        posterior = likelihoods * np.array(prior)
        posterior = posterior / posterior.sum()

        return {f"Goal_{i}": p for i, p in enumerate(posterior)}


class ObservationGenerator:


    def __init__(self, domain_path: str, problem_template: str, planner_command: List[str]):
        self.domain_path = domain_path
        self.problem_template = problem_template
        self.planner_command = planner_command

    def generate_plan(self, goal: str) -> Tuple[List[str], float]:

        # Create problem with this goal
        problem_content = Path(self.problem_template).read_text()
        goal_pattern = r'\(:goal\s+.+?\)'
        problem_content = re.sub(goal_pattern, f'(:goal {goal})', problem_content, flags=re.DOTALL)

        with tempfile.TemporaryDirectory() as tmpdir:
            problem_file = Path(tmpdir) / "problem.pddl"
            problem_file.write_text(problem_content)

            # Run planner
            cmd = self.planner_command + [self.domain_path, str(problem_file)]
            result = subprocess.run(cmd, capture_output=True, text=True)

            if result.returncode == 0:
                # Parse plan from output
                actions = []
                for line in result.stdout.split('\n'):
                    line = line.strip()
                    if line and line.startswith('('):
                        actions.append(line)
                return actions, len(actions)

        return [], float('inf')

    def generate_observation_prefix(
        self,
        goal: str,
        observation_ratio: float
    ) -> Tuple[List[Observation], str]:

        plan, plan_length = self.generate_plan(goal)

        if not plan:
            return [], goal

        n_obs = max(1, int(len(plan) * observation_ratio))
        observed_actions = plan[:n_obs]

        observations = []
        for action_str in observed_actions:
            obs = self._parse_action(action_str)
            observations.append(obs)

        return observations, goal

    def _parse_action(self, action_str: str) -> Observation:
        """Parse a PDDL action string into an Observation object"""
        # Remove parentheses
        action_str = action_str.strip()
        if action_str.startswith('(') and action_str.endswith(')'):
            action_str = action_str[1:-1]

        parts = action_str.split()
        action_name = parts[0]
        parameters = parts[1:] if len(parts) > 1 else []

        return Observation(action_name=action_name, parameters=parameters)


# Example usage and testing
if __name__ == "__main__":
    # Example: Block World domain
    sample_domain = """
(define (domain blocks)
  (:requirements :strips)
  (:predicates
    (clear ?x)
    (on ?x ?y)
    (ontable ?x)
    (holding ?x)
    (handempty)
  )
  (:action pickup
    :parameters (?x)
    :precondition (and (clear ?x) (ontable ?x) (handempty))
    :effect (and (holding ?x) (not (clear ?x)) (not (ontable ?x)) (not (handempty)))
  )
  (:action putdown
    :parameters (?x)
    :precondition (holding ?x)
    :effect (and (clear ?x) (ontable ?x) (handempty) (not (holding ?x)))
  )
  (:action stack
    :parameters (?x ?y)
    :precondition (and (holding ?x) (clear ?y))
    :effect (and (on ?x ?y) (clear ?x) (handempty) (not (holding ?x)) (not (clear ?y)))
  )
)
"""

    sample_problem = """
(define (problem blocks-problem)
  (:domain blocks)
  (:objects a b c)
  (:init
    (ontable a)
    (ontable b)
    (ontable c)
    (clear a)
    (clear b)
    (clear c)
    (handempty)
  )
  (:goal (and (on a b) (on b c)))
)
"""

    # Write sample files
    Path("/tmp/sample_domain.pddl").write_text(sample_domain)
    Path("/tmp/sample_problem.pddl").write_text(sample_problem)

    # Test compiler
    compiler = PDDLCompiler("/tmp/sample_domain.pddl", "/tmp/sample_problem.pddl")

    observations = [
        Observation("pickup", ["a"]),
        Observation("stack", ["a", "b"])
    ]

    # Compile compliant problem
    dom, prob = compiler.compile_compliant(observations, Path("/tmp/test_output"))
    print(f"Compliant domain: {dom}")
    print(f"Compliant problem: {prob}")

    # Show output
    print("\n--- Compiled Compliant Domain ---")
    print(Path(dom).read_text()[:500] + "...")

    print("\n--- Compiled Compliant Problem ---")
    print(Path(prob).read_text())